# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.16.1

pipelines:
  branches:
    development:
      - step:
         deployment: test
         name: Zipping Application
         script:
         - git archive --format=tar.gz development -o application.tar.gz
         artifacts: 
         - application.tar.gz
      - step:
         name: Uploading to Heroku Test Server
         script:
         - pipe: atlassian/heroku-deploy:1.1.3
           variables:
             HEROKU_API_KEY: $HEROKU_KEY
             HEROKU_APP_NAME: 'speedymobile-test'
             ZIP_FILE: 'application.tar.gz'
    master:
      - step:
         deployment: production
         name: Installing Dependencies & Building Application
         caches:
         - node
         script:
         - npm install
         - npm run build
         - apt-get update
         - apt-get install zip
         - zip application.zip -r dist HTML images public static package.json package-lock.json
         artifacts: 
         - application.zip
      - step:
         name: Uploading to AWS Elastic Beanstalk
         script:
             - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.2
               variables:
                 AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                 AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                 AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                 APPLICATION_NAME: 'speedymobile-web-api'
                 ENVIRONMENT_NAME: 'speedymobile-env'
                 ZIP_FILE: 'application.zip'
                 WAIT: 'true'
                 S3_BUCKET: $S3_BUCKET
