export type CheckoutState = {
	firstName: string;
	lastName: string;
	email: string;
	phoneNumber: string;
	address: string;
	city: string;
	province: string;
	postalCode: string;
	billingFirstName: string;
	billingLastName: string;
	billingAddress: string;
	billingCity: string;
	billingProvince: string;
	billingPostalCode: string;
	cardNumber: string;
	securityCode: string;
	expirationMonth: string;
	expirationYear: string;
	deliveryCost: number;
	deliveryType: string;
	check1: boolean;
	check2: boolean;
	check3: boolean;
	loading: boolean;
	error: boolean;
	subscribe: string;
	subscribeState: boolean | null;
	unSubscribeState: boolean | null;
};
